
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[functions]]
  path = "netlify/functions/dist/live-coin-watch-sync.js"
  schedule = "*/5 * * * *"

[[redirects]]
  from = "/api/token/*"
  to = "/.netlify/functions/token"
  status = 200

[[redirects]]
  from = "/api/holders/*"
  to = "/.netlify/functions/holders"
  status = 200

[[redirects]]
  from = "/api/transactions/*"
  to = "/.netlify/functions/transactions"
  status = 200

[[redirects]]
  from = "/api/network-status"
  to = "/.netlify/functions/network-status"
  status = 200

[[redirects]]
  from = "/api/live-coin-watch/*"
  to = "/.netlify/functions/live-coin-watch-status"
  status = 200

[[redirects]]
  from = "/api/token-supply-data"
  to = "/.netlify/functions/token-supply-data"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
