/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TriangularArbExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aavePool"
      | "eloquraRouter"
      | "eloquraWeth"
      | "execute"
      | "executeOperation"
      | "executeWithFlashloan"
      | "owner"
      | "rescueETH"
      | "rescueTokens"
      | "uniswapRouter"
      | "uniswapWeth"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "aavePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eloquraRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eloquraWeth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike[],
      AddressLike[],
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOperation",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithFlashloan",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike[],
      AddressLike[],
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "rescueETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapWeth",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eloquraRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eloquraWeth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithFlashloan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rescueETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapWeth",
    data: BytesLike
  ): Result;
}

export interface TriangularArbExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): TriangularArbExecutor;
  waitForDeployment(): Promise<this>;

  interface: TriangularArbExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aavePool: TypedContractMethod<[], [string], "view">;

  eloquraRouter: TypedContractMethod<[], [string], "view">;

  eloquraWeth: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [
      direction: BigNumberish,
      inputToken: AddressLike,
      amountIn: BigNumberish,
      eloquraPath1: AddressLike[],
      eloquraPath2: AddressLike[],
      uniswapTokenIn: AddressLike,
      uniswapTokenOut: AddressLike,
      uniswapFeeTier: BigNumberish,
      minProfit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  executeOperation: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      premium: BigNumberish,
      initiator: AddressLike,
      params: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  executeWithFlashloan: TypedContractMethod<
    [
      direction: BigNumberish,
      inputToken: AddressLike,
      amountIn: BigNumberish,
      eloquraPath1: AddressLike[],
      eloquraPath2: AddressLike[],
      uniswapTokenIn: AddressLike,
      uniswapTokenOut: AddressLike,
      uniswapFeeTier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rescueETH: TypedContractMethod<[], [void], "nonpayable">;

  rescueTokens: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  uniswapRouter: TypedContractMethod<[], [string], "view">;

  uniswapWeth: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eloquraRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eloquraWeth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      direction: BigNumberish,
      inputToken: AddressLike,
      amountIn: BigNumberish,
      eloquraPath1: AddressLike[],
      eloquraPath2: AddressLike[],
      uniswapTokenIn: AddressLike,
      uniswapTokenOut: AddressLike,
      uniswapFeeTier: BigNumberish,
      minProfit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeOperation"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      premium: BigNumberish,
      initiator: AddressLike,
      params: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeWithFlashloan"
  ): TypedContractMethod<
    [
      direction: BigNumberish,
      inputToken: AddressLike,
      amountIn: BigNumberish,
      eloquraPath1: AddressLike[],
      eloquraPath2: AddressLike[],
      uniswapTokenIn: AddressLike,
      uniswapTokenOut: AddressLike,
      uniswapFeeTier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rescueETH"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueTokens"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uniswapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "uniswapWeth"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
