/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEloquraFactory,
  IEloquraFactoryInterface,
} from "../../../contracts/EloquraPair.sol/IEloquraFactory";

const _abi = [
  {
    inputs: [],
    name: "feeTo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEloquraFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IEloquraFactoryInterface {
    return new Interface(_abi) as IEloquraFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEloquraFactory {
    return new Contract(address, _abi, runner) as unknown as IEloquraFactory;
  }
}
