/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEloquraCallee,
  IEloquraCalleeInterface,
} from "../../../contracts/EloquraPair.sol/IEloquraCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "eloquraCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEloquraCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IEloquraCalleeInterface {
    return new Interface(_abi) as IEloquraCalleeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEloquraCallee {
    return new Contract(address, _abi, runner) as unknown as IEloquraCallee;
  }
}
